/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AudioTags {
  title?: string
  artists?: Array<string>
  album?: string
  year?: number
  genre?: string
  track?: Position
  albumArtists?: Array<string>
  comment?: string
  disc?: Position
}

export declare function clearTags(filePath: string): Promise<void>

export interface Position {
  no?: number
  of?: number
}

export declare function readCoverImage(buffer: Buffer): Promise<Buffer | null>

export declare function readTags(filePath: string): Promise<AudioTags>

export declare function readTagsFromBuffer(buffer: Buffer): Promise<AudioTags>

export declare function writeCoverImage(buffer: Buffer, imageData: Buffer): Promise<Buffer>

export declare function writeTags(filePath: string, tags: AudioTags): Promise<void>

export declare function writeTagsToBuffer(buffer: Buffer, tags: AudioTags): Promise<Buffer>
