[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.'cfg(target_vendor = "apple")']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains"]

# To be able to run unit tests on Linux, support compilation to 'x86_64-unknown-linux-gnu'.
# pthread_key_create() destructors and segfault after a DSO unloading https://sourceware.org/bugzilla/show_bug.cgi?id=21031
[target.'cfg(all(target_os = "linux", target_env = "gnu"))']
rustflags = [
  "-C",
  "link-args=-Wl,--warn-unresolved-symbols",
  "-C",
  "link-args=-Wl,-z,nodelete",
]

# To be able to run unit tests on Windows, support compilation to 'x86_64-pc-windows-msvc'.
[target.'cfg(target_env = "msvc")']
rustflags = ["-C", "link-args=/FORCE"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.wasm32-wasip1-threads]
rustflags = ["-C", "target-feature=+simd128", "--cfg", "tokio_unstable"]
