[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.arm-unknown-linux-gnueabihf]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]
